name: ci

inputs:
  docker_username:
    description: 'Username of the docker repo'
  docker_token:
    description: 'Token of the user'

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.docker_username }}
          password: ${{ inputs.docker_token }}

      - name: Push Docker Image
        run: docker push ${{ env.DOCKER_IMAGE_NAME }}
        shell: bash